### ISSUE TITLE
RuntimeError：“not enough space”

### ISSUE THREAD

**Issue by REBE0304** [hulianyuyy/CorrNet#1]
遇到的问题：
尝试训练该源码的模型时，总在第一轮epoch结束时出现“not enough space”的问题。已尝试了许多方法，例如调整batchsize、num_worker参数等方法，仍然解决不了。

请求帮助：
想询问一下作者训练模型所用的硬件配置，排查一下是否为硬件条件不够的原因。

本人的环境配置：
环境：python3.6.7，pytorch1.9.0，ctcdecode0.4。
硬件：显卡4张4090，内存125G。

**Comment by hulianyuyy** [comment]
这个问题大概率是因为硬盘没有空间了，建议检查一下。错误很可能是‘Not enough space on disk’

**Comment by REBE0304** [comment]
你的邮件我收到了哦~----夏爱灵

**Comment by stevenGX24** [comment]
请问ctcdecode 1.0.3在哪里下载呢？我也遇到了同样的问题。

**Comment by REBE0304** [comment]
你的邮件我收到了哦~----夏爱灵

**Comment by hulianyuyy** [comment]
You can download and install ctcdecode [here](https://github.com/parlance/ctcdecode). But i don't exactly know what's the 1.0.3 version of ctcdecode. Normally, it's 0.4.0.

**Comment by stevenGX24** [comment]
Appreciated😀

**Comment by LiPeng-China** [comment]
> 感谢！问题已解决，已排查过硬盘空间没有问题，然后排查到应该还是环境版本问题，环境重新配置到pytorch1.13.0和ctcdecode1.0.3版本后就可以正常训练，低于这个版本就会有“not enough space”的报错。

您好，我最近也碰到了相同的问题。但是在网上没找到ctcdecode1.0.4版本的下载包，请问您有相关下载链接没有？非常感谢！

**Comment by REBE0304** [comment]
你的邮件我收到了哦~----夏爱灵

**Comment by LiPeng-China** [comment]
> 感谢！问题已解决，已排查过硬盘空间没有问题，然后排查到应该还是环境版本问题，环境重新配置到pytorch1.13.0和ctcdecode1.0.3版本后就可以正常训练，低于这个版本就会有“not enough space”的报错。

您好，我最近也碰到了相同的问题。但是在网上没找到ctcdecode1.0.3版本的下载包，请问您有相关下载链接没有？非常感谢！

**Comment by REBE0304** [comment]
> > 谢谢！问题已解决，已排查过硬盘空间没有问题，然后排查到应该还是环境版本问题，环境重新配置到pytorch1.13.0和ctcdecode1.0.3版本后就正常训练了，低于这个版本就会有“not” “足够的空间”的报错。
> 
> 您好，我最近也查到了同样的问题。但是在网上没有找到ctcdecode1.0.3版本的下载包，请问您有相关的下载链接吗？非常感谢！

不好意思，回去看了眼我的ctcdecode，好当时下载的包名字是1.0.3，但安装好后conda list查看其实还是0.4.0的🤦‍。建议还是换个pytorch的版本看看。
