### ISSUE TITLE
RuntimeError: Invalid UTF-8

### ISSUE THREAD

**Issue by percise** [hulianyuyy/CorrNet#17]
你好，出现了
RuntimeError: Invalid UTF-8 错误，这是因为ctcdecode的问题吗，已经按照你的要求安装了3.7.1 pyotrch1.10.1 cuda11.1，ctcdecode0.4，是因为评估工具没有安装好嘛 kaldi已经软链接到software文件下，warp-ctc是0.1的版本根据要求都已安装好，不知是什么原因，求指教

**Comment by percise** [comment]
![4690b8dfb36671f90b3596d09b12aa9](https://github.com/hulianyuyy/CorrNet/assets/88238940/195334a3-e7d4-4ca0-a852-c890db8d8355)
附上出错的代码图，求告知

**Comment by percise** [comment]
> [有人](https://github.com/parlance/ctcdecode/issues/108)也遇到过这个问题，但我也不知道如何解决。这主要是由 ctcdecode 造成的。

收到 感谢回复  我再研究一下

**Comment by hulianyuyy** [comment]
The solution can be referred [here](https://drive.google.com/drive/folders/1DPw3ilDejLBiSx3E2vGfOrKWJyVw19WH?usp=sharing).

**Comment by youthxin** [comment]
请问你解决了这个问题吗，我也遇到了这样的问题

**Comment by hulianyuyy** [comment]
可以参照上面解决
