### ISSUE TITLE
video_map.txt in dataset_preprocess_CSL-dairy

### ISSUE THREAD

**Issue by btt-creator** [hulianyuyy/CorrNet#18]
Hi，author！May i ask you how to get video_map.txt in dataset_preprocess_CSL-dairy?just translate csl2020ct_v1.pkl to video_map.txt?
![image](https://github.com/hulianyuyy/CorrNet/assets/92516701/3994fdb1-aed9-41d9-89da-72145bbf2895)

**Comment by hulianyuyy** [comment]
You could find useful files [here](https://drive.google.com/drive/folders/1DPw3ilDejLBiSx3E2vGfOrKWJyVw19WH?usp=sharing).
