### ISSUE TITLE
Fixed Frames

### ISSUE THREAD

**Issue by atonyo11** [hulianyuyy/CorrNet#24]
Sorry if I misunderstood. Usually, we need to set a constant for number of frame in a video when fitting through network. I can't find how you set the number of frames for a video to training (some thing like MAX_SEQ_LENGTH or Fixed_Frames). I can see the class TemporalRescale(object) in utils, but I think it will create clips of different lengths. Can you tell me how did you do?

Thanks!

**Comment by hulianyuyy** [comment]
In CorrNet, we don't set a constant number for frames in a video, but send all frames into the model. Videos in a batch will be padded into the maximum length of videos in the same batch.

**Comment by atonyo11** [comment]
I got it. Thank you very much!
