### ISSUE TITLE
Issue with extracting the CSL-Daily Dataset

### ISSUE THREAD

**Issue by snalyami** [hulianyuyy/CorrNet#28]
First of all thank you very much for open sourcing your code. I have an issue unrelated to your code, but I'm hoping I can get some help. I dowloaded the CSL-Daily dataset parts csl-daily-frames-512x512.tar.gz_00 - csl-daily-frames-512x512.tar.gz_09 and followed the instructions to cat them and extract the files. However, I can only extract the files from the first concatenated archive  (csl-daily-frames-512x512.tar.gz_00). I would really appreciate your help, if you have experienced this.

**Comment by hulianyuyy** [comment]
Have you first run ```cat xxx.tar.gz* ``` >>xxx.tar.gz, and then run tar  -vzxf  xxx.tar.gz?

**Comment by snalyami** [comment]
Yes I did.

**Comment by hulianyuyy** [comment]
It's a strange problem, and i feel sorry that i have no clues.
