### ISSUE TITLE
issue with installing module like CTC,sclite [kaldi-asr/kaldi] and SeanNaren/warp-ctc

### ISSUE THREAD

**Issue by ethio-artifical** [hulianyuyy/CorrNet#29]
I am having problems installing modules like CTC, scliter [kaldi-asr/kaldi] and SeanNaren/warp-ctc I am using Google Colab to install it. So can you give me basic requirement like PyTorch,python version and other required modules to successfully run the code?

**Comment by hulianyuyy** [comment]
For pytorch, you could install torch==1.13.0. For python you could install python==3.9.0. For other modules, you could run ``pip install -r requirements.txt``.

**Comment by shizukadara** [comment]
I am having problem installing ctcdecode on windows 11. Is it not compatible for windows?

**Comment by shizukadara** [comment]
> For pytorch, you could install torch==1.13.0. For python you could install python==3.9.0. For other modules, you could run `pip install -r requirements.txt`.


I am having problem installing ctcdecode on windows 11. Is it not compatible for windows? I am using python 3.9, torch 2.0, cuda 11.8. Is ctcdecode not compatible with windows? because I was able to install it on colab.

**Comment by hulianyuyy** [comment]
Ctcdecode does not support windows currently.
