### ISSUE TITLE
Weigh Tensor fill with tensor of 0

### ISSUE THREAD

**Issue by OssamaChrifi** [hulianyuyy/CorrNet#3]
Hello, i try to run your work in windows systeme but i had some error : 

Here we see, with the debug, that the weight tensor is correctly initialized : 

![image](https://user-images.githubusercontent.com/93863424/230366450-9bdfe18a-a44e-47b2-bcbb-1b9a288b0452.png)

but when this commande is run in the seq_scripts function :  

for batch_idx, data in enumerate(tqdm(loader)) 

the weigh tensor is put to 0 :

![image](https://user-images.githubusercontent.com/93863424/230367523-e5a8cb89-07ea-42ee-b2e7-184ec6246dfb.png)

Systeme : 
Pythorch 2.0

i work with 1 GPU, when i run the resnet.py alone the wheigh is correctly initialized and the convolution work correctly.

when i try to entre in this line with the debug : for batch_idx, data in enumerate(tqdm(loader)) 

it send me in the file comm.py in /modules/sync_batchnorm in the class SyncMaster :

def __getstate__(self):
        return {'master_callback': self._master_callback}

**Comment by hulianyuyy** [comment]
Sorry, i can't give an exact answer. But i suppose that the initializations are skipped for these tensors if you enter this line with the debug : for batch_idx, data in enumerate(tqdm(loader)).
