### ISSUE TITLE
Grad-Cam

### ISSUE THREAD

**Issue by snalyami** [hulianyuyy/CorrNet#30]
Thank you for your efforts in this project. 

I'm trying to plot the activation maps of the conv2d module, like figure 1 in your paper. I've used this Grad-Cam usage example as a start point: https://github.com/jacobgil/pytorch-grad-cam/blob/master/usage_examples
However, I'm getting an error, which I think is  because, the model returns a dic and Grad-CAM methods expect a single output.  
Also, the model takes the video and video length as input, but Grad-CAM methods take only one input_tensor (image). 

I would really appreciate if you would share the visualization code you used in your paper, or help me figure out these problems. 

Thank you again for your continuous support.

**Comment by hulianyuyy** [comment]
I'm working on  some other things these days. I have updated the readme.md and you can follow it to perform visualization.
