### ISSUE TITLE
CSL dataset fails to generate tmp2.ctm to complete validation

### ISSUE THREAD

**Issue by xuqico** [hulianyuyy/CorrNet#31]
Hi author, I got the following error when I am automatically performing the validation after the first round of training on the CSL dataset, I realized that I can't generate the tmp2.ctm file, I tried deleting the line breaks in . /evaluation/slr_eval/preprocess.sh: line 2: $'\r' line breaks are deleted, but it still can't generate tmp2.ctm file, just ". /evaluation/slr_eval/preprocess.sh: line 2: $'\r': command not found", but still can't solve the other problems, what should I do?

Here are the corresponding errors
./evaluation/slr_eval/preprocess.sh: line 2: $'\r': command not found
./evaluation/slr_eval/preprocess.sh: line 21: syntax error: unexpected end of file
Traceback (most recent call last):
  File "./evaluation/slr_eval/mergectmstm.py", line 9, in <module>
    ctm = open(ctmFile, "r")
FileNotFoundError: [Errno 2] No such file or directory: './work_dir/baseline/tmp2.ctm'
cp: cannot stat './work_dir/baseline/tmp2.ctm': No such file or directory
Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    processor.start()
  File "main.py", line 70, in start
    dev_wer = seq_eval(self.arg, self.data_loader['dev'], self.model, self.device,
  File "/root/CorrNet (copy)/seq_scripts.py", line 95, in seq_eval
    del conv_ret
UnboundLocalError: local variable 'conv_ret' referenced before assignment

**Comment by hulianyuyy** [comment]
May i ask you which operation system you use? Actually, i even can't fine $'\r in line 2 of preprocess.sh.

**Comment by xuqico** [comment]
我是在autodl服务器，Ubuntu上跑的。我在跑VAC项目的时候没有出现这个问题，但是不知道为什么跑CorrNet项目的CSL数据集时出现了我提到的报错

**Comment by hulianyuyy** [comment]
‘\r’'\n' represents the line feed command in the windows system, '\n' represents the line feed command in the unix/ubuntu system. Maybe you could delete this line in the ubuntu system, and then create a new blank line to try it?

**Comment by xuqico** [comment]
好的，我尝试一下

**Comment by xuqico** [comment]
Problem solved, it's working fine
