### ISSUE TITLE
del/ins

### ISSUE THREAD

**Issue by atonyo11** [hulianyuyy/CorrNet#32]
Dear author,
How to know del/ins after training/inference? in logs (or something like log)?

**Comment by hulianyuyy** [comment]
You can view the del/ins in .sys file of the "epoch_xx_result" dir in your work_dir.

**Comment by atonyo11** [comment]
I got it, thank you!

**Comment by kido1412y2y** [comment]
> You can view the del/ins in .sys file of the "epoch_xx_result" dir in your work_dir.
Hello author, I found the del/ins of Dev in the "epoch xx result" folder. How can I view the del/ins of Test?

**Comment by hulianyuyy** [comment]
You should first perform inference to get the results on the test set, and then view the del/ins of Test.

**Comment by kido1412y2y** [comment]
> You should first perform inference to get the results on the test set, and then view the del/ins of Test.

Thank you, I found it！

**Comment by atonyo11** [comment]
Should I  view the del/ins in out.output-hypothesis-dev-conv.ctm.sys or out.output-hypothesis-dev.ctm.sys file? and Should I take  Sum/Avg, Mean,  S.D., Median as your paper? Thank!
![image](https://github.com/hulianyuyy/CorrNet/assets/149935186/2aa66fe8-3756-4b31-b50d-72c8fd8813f5)

**Comment by hulianyuyy** [comment]
You should view the out.output-hypothesis-dev.ctm.sys file, and view the Sum/Avg.

**Comment by atonyo11** [comment]
Thank you!
