### ISSUE TITLE
Calculate the delta t

### ISSUE THREAD

**Issue by atonyo11** [hulianyuyy/CorrNet#36]
https://github.com/hulianyuyy/CorrNet/blob/9ad569727be617cf614b19aecb79b8e625a9bd7d/dataset/dataloader_video.py#L129-L140

Hi author, I did not understand why we do that. Can you explain how to calculate the delta t? For example C5-P2-C5-P2? Thank you in advance!

![image](https://github.com/hulianyuyy/CorrNet/assets/149935186/a87febcb-bcde-4581-8fee-7ffc0c73f4e5)

**Comment by hulianyuyy** [comment]
The padding after a C5 is (5-1)/2 = 2. After P2, it becomes 2*2=4. After C5, it becomes 4+2=6. Finally after P2, it becomes 6*2=12. This is the calculation process of the padding, which may have different meanings with delta t in your picture.

**Comment by atonyo11** [comment]
I got it. Thank you!
