### ISSUE TITLE
CSL dataset preprocessing failed

### ISSUE THREAD

**Issue by kido1412y2y** [hulianyuyy/CorrNet#42]
Hello, can you provide the file tree for the CSL dataset?

When I ran the Python data_process CSL. py -- process image -- multiprocessing code, I couldn't find a feature map resized to 256 x 256.

Is there an error in the CSL dataset I downloaded?

This is the file tree of my CSL dataset

![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/4becb479-3728-4fab-9ca9-a771493d1fb1)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/53d5a51c-b6ba-4d00-b347-10b84bd8174e)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/eae49b90-25c1-41f8-9656-b5ba0c58af4b)

**Comment by hulianyuyy** [comment]
![image](https://github.com/hulianyuyy/CorrNet/assets/29403866/4c05e1a8-9c9a-4f9c-8e53-d51acdc5d65c)
This is the file tree in my CSL dataset. The authors seem to re-origanize the datasets in a different way from what they release to me. The overall files should be the same.

**Comment by kido1412y2y** [comment]
@hulianyuyy 
Can you provide what a file tree looks like under video0? I want to correct my file name in order to complete the image size adjustment of 256 x 256. For example, video0, video1, video2, video3... How many folders are there called "video+numbers" (100?), and then open video0. What are there inside? How many files are there (50?), and further open the folder. What is inside? How many files are there (50?), and finally open the folder. What are the names of the pictures inside?
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/6727cdb8-9392-44f3-9654-f1050eb020fd)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/489c06f5-fde8-4aea-897c-4dfee79d7107)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/bec87e2c-b8df-4ee8-b610-61f230c6c64d)

**Comment by hulianyuyy** [comment]
There are 25000 folders under this directory which are called like "video+numbers". For each folder like video0, there are images with various nums for different folders. You can view the file tree with video and image names as follows.
![image](https://github.com/hulianyuyy/CorrNet/assets/29403866/0699b474-d0dc-4e3c-85fe-abe4d7457add)
![image](https://github.com/hulianyuyy/CorrNet/assets/29403866/f99d7931-412e-4d1f-9f90-c0a5ec6567e1)

**Comment by kido1412y2y** [comment]
@hulianyuyy 
Hello author, I'm very sorry. CSL has a total of 25000 samples, which should be video0, video1, video2... video25000. I found a folder named "video+numbers" with numbers exceeding 25000 while checking the tags. for example，video8807，video8900...
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/5d344576-0a62-4c9c-9f07-dcf944003f3c)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/15099fff-562a-4a4b-afd3-6f2fbbd91ff4)
![image](https://github.com/hulianyuyy/CorrNet/assets/97590692/0f2ffe2c-9762-4ac3-b7cf-25a8ec238cf3)
May I ask if it is possible to provide your version of the CSL dataset.This is my email: 1531720969@qq.com

**Comment by hulianyuyy** [comment]
Sorry, as we have signed a data releasement aggrement when we request the data from the authors, we can't release the data without their aggrement. You may request the data from the authors by the email？

**Comment by kido1412y2y** [comment]
Thank you，I'll give it a try
