### ISSUE TITLE
Train Problem

### ISSUE THREAD

**Issue by xxxiaosong** [hulianyuyy/CorrNet#43]
Hello! When training on the csl-daily dataset, the following error is reported midway through the first epoch. I don't know what caused the mistake. I am very eager to get your help
![error](https://github.com/hulianyuyy/CorrNet/assets/136720538/0b3f1b87-c7fd-4339-9e10-14a8b1aaeb4d)

**Comment by xxxiaosong** [comment]
Thanks for your reply! The problem is indeed as you said.

**Comment by hj22222222** [comment]
> Thanks for your reply! The problem is indeed as you said.

hello, I have the same error on CSL-Daily dataset, could you tell me how to solve this problem ?
