### ISSUE TITLE
Problems with test_one_video.py using CSL-Daily dataset

### ISSUE THREAD

**Issue by lightandfuture** [hulianyuyy/CorrNet#45]
I tried with the test_one_video.py with CSL-Daily and some issues occurred. I tested it with the following 4 datasets from CSL-Daily, and all of them are not giving out the correct answers.

-----------------------------------------------------------------------------------------------------------------------------------------
**_Datasets:_**
1. S000000_P0000_T00
2. S000003_P0000_T00
3. S000000_P0008_T00
4. S000009_P0008_T00
-----------------------------------------------------------------------------------------------------------------------------------------
**_Errors:_**
2. (S000003_P0000_T00)
(corrNet) ubuntu@Washington:home/CorrNet$ python test_one_video.py
test_one_video.py:54: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  video_length = torch.LongTensor([np.ceil(vid.size(1) / total_stride) * total_stride + 2*left_pad ])
output glosses : [[('有', 0)]]
##################################################################
3. (S000000_P0008_T00)
(corrNet) ubuntu@Washington:home/CorrNet$ python test_one_video.py
test_one_video.py:54: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  video_length = torch.LongTensor([np.ceil(vid.size(1) / total_stride) * total_stride + 2*left_pad ])
output glosses : [[('2', 0)]]
##################################################################
4. (S000009_P0008_T00)
(corrNet) ubuntu@Washington:~/CorrNet$ python test_one_video.py
test_one_video.py:54: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  video_length = torch.LongTensor([np.ceil(vid.size(1) / total_stride) * total_stride + 2*left_pad ])
output glosses : [[('山', 0), ('雪', 1)]]

-----------------------------------------------------------------------------------------------------------------------------------------
**_Video Maps:_**
1. 000000|S000000_P0000_T00|52|你们 好|你 们 好 ！|你们 好 ！|r a w
2. 000003|S000001_P0000_T00|37|对不起|对 不 起 ！|对不起 ！|v w
3. 000000|S000000_P0000_T00|52|你们 好|你 们 好 ！|你们 好 ！|r a w
4. 000009|S000003_P0000_T00|30|谢谢|谢 谢 ！|谢谢 ！|v w

-----------------------------------------------------------------------------------------------------------------------------------------
**_PS:_**
Although dataset_1 and dataset_3 have the same meanings, they are performed by different person and the result seems to be different. For dataset_1, we got [[('5', 0)]], and for dataset_3 we got [[('2', 0)]].

Can you help me with this problem? I am new to this area and I can't really figure out the problem myself. Thank you!

**Comment by hulianyuyy** [comment]
I have tested the file and can get correct results. May i ask if you have loaded the pretrained weights for CSL-daily dataset? Or maybe you can first load the weights for inference and see if it could reach 30.6 WER. A similar [issue](https://github.com/hulianyuyy/CorrNet/issues/27) has been raised before.

**Comment by lightandfuture** [comment]
> I have tested the file and can get correct results. May i ask if you have loaded the pretrained weights for CSL-daily dataset? Or maybe you can first load the weights for inference and see if it could reach 30.6 WER. A similar [issue](https://github.com/hulianyuyy/CorrNet/issues/27) has been raised before.

Yes, I have loaded the pretrained weights provided, and I also checked the resnet.py and adjusted it according to the readme file.

Here are the files :
[resnet.txt](https://github.com/hulianyuyy/CorrNet/files/14852248/resnet.txt)
[test_one_video.txt](https://github.com/hulianyuyy/CorrNet/files/14852254/test_one_video.txt)

I'm sorry but I didn't seem to find the solution to issue#27.

**Comment by hulianyuyy** [comment]
I have checked your files and don't see any errors. I still can't figure out the issue. Maybe this issue only happens on the CSL-Daily dataset. Have you tested the test_one_video.py upon the phoenix14 dataset? Could it provide the correct outputs?

**Comment by lightandfuture** [comment]
> I have checked your files and don't see any errors. I still can't figure out the issue. Maybe this issue only happens on the CSL-Daily dataset. Have you tested the test_one_video.py upon the phoenix14 dataset? Could it provide the correct outputs?

Sorry for the late reply. Yes, test_one_video.py worked fine upon the phoenix14 dataset on our device.

**Comment by hulianyuyy** [comment]
I concurrently don't have an exact answer for this question. Can you get 30.1 WER on the CSL-Daily dataset with the pretrained weight? It's strange that the test_one_video.py performs normally on my device.
