### ISSUE TITLE
Preprocessing Phoenix 2014 -T 

### ISSUE THREAD

**Issue by itsjustfons** [hulianyuyy/CorrNet#46]
Currently trying to resize the Phoneix-2014-T dataset. I followed the procedure in making the symbolic link as well as setting the dataset-root to the correct filepath. When I run dataset_preprocess-T.py , the tqdm bars load as usual in the command line like what happens with dataset_preprocess.py. At the end of the process however, none of the images are resized to 256x256. There also is no "256x256 " folder made. 

I did some digging and found that line 64 may not be working right
`  `  img_list = glob.glob(f"{info_dict['prefix']}/{info['folder']}")``

the variable img_list keeps coming up empty whenever I check it. This is however not the case with dataset_preprocess.py. Is there a fix for this?

**Comment by hulianyuyy** [comment]
You may refer to [this issue](https://github.com/hulianyuyy/CorrNet/issues/10#issuecomment-1660363025) to check if you have the same problem. Otherwise, you may output the folder of the img_list and see if there are images under it.

**Comment by itsjustfons** [comment]
It worked! Thanks
