### ISSUE TITLE
The log file for CSL dataset

### ISSUE THREAD

**Issue by xuqico** [hulianyuyy/CorrNet#47]
Hello can you provide your CSL log file? I may have some problems with mine and I would like to see your process

**Comment by xuqico** [comment]
I tried run the default code to train CSL dataset. This is log fie:
[log.txt](https://github.com/hulianyuyy/CorrNet/files/15056019/log.txt)
What could be the reason why the first training training trend is good but in the middle the results become poor?

**Comment by hulianyuyy** [comment]
This dataset is easily overfitting. I have lost the original log file. There are [some tricks](https://github.com/VIPL-SLP/VAC_CSLR/issues/17) when training on this dataset.

**Comment by xuqico** [comment]
> This dataset is easily overfitting. I have lost the original log file. There are [some tricks](https://github.com/VIPL-SLP/VAC_CSLR/issues/17) when training on this dataset.

Thank you for your prompt reply!
So I should go and tweak the relevant parameters in the configs so that it doesn't overfit easily right?

**Comment by hulianyuyy** [comment]
Yes, you may kindly tweak the parameters or use other techniques to avoid overfitting.

**Comment by xuqico** [comment]
Well thank you for your prompt reply, I am currently actively adjusting the relevant parameters
