### ISSUE TITLE
Can you share your environment.yml conda environment?

### ISSUE THREAD

**Issue by argadewanata** [hulianyuyy/CorrNet#48]
I'm facing a bit of a challenge installing ctcdecode since it doesn't support every PyTorch version. I really want to match all the exact versions of your libraries. So, can you share your environment.yml conda environment?

**Comment by hulianyuyy** [comment]
Sure, i have uploaded the environment.yaml.

**Comment by argadewanata** [comment]
Thank you so much for fulfilling my request, I really appreciate your help
