### ISSUE TITLE
Is it possible to utilize a custom DIY dataset with this architecture?

### ISSUE THREAD

**Issue by argadewanata** [hulianyuyy/CorrNet#49]
I'm considering implementing it for my country's sign language.

**Comment by hulianyuyy** [comment]
Yes, you may refer to the [preprocess.py](https://github.com/hulianyuyy/CorrNet/blob/main/preprocess/dataset_preprocess.py) and generate the video path, gloss labels as well as other necessary information into a series of .npy files first, and then load the dataset in the [dataloader_video.py](https://github.com/hulianyuyy/CorrNet/blob/main/dataset/dataloader_video.py).

**Comment by argadewanata** [comment]
As far as i know, there is no gloss translation available for the sign language used in my country. Can I proceed solely with the sign translation?

**Comment by hulianyuyy** [comment]
This reop currently only supports CSLR, which uses glosses as outputs. For sign translation, you may use models that support the sign language translation (SLT) task.
