### ISSUE TITLE
Training Problem

### ISSUE THREAD

**Issue by yemenoglu** [hulianyuyy/CorrNet#5]
Hi, i used CorrNet to train on the PHOENIX-2014-T dataset, in Training section at your shared page (https://github.com/hulianyuyy/CorrNet) i am taking this error (No module named 'dataset.dataloader_video'). I added dataset and datasets modules via pip install, but still i am taking same error. And, before Training section, if i use this command (python main.py --device your_device --load-weights path_to_weight.pt --phase test), i am taking this error (No such file or directory: 'path_to_weight.pt'
), i don't know how to i get this .pt file.  
Could you help me, please. 
Thank you.

**Comment by hulianyuyy** [comment]
This is not a module. It's a py file, located in dataset/dataloader_video.py. Normally, this error won't incur. Please check if this file exists. You can comment if you have further question.

**Comment by yemenoglu** [comment]
Yes, it is inside of dataset folder, but still same error, sorry.

**Comment by hulianyuyy** [comment]
I have downloaded the repo from gihub and retrain it. But i haven't encounetered this issue. Maybe you can try adding the path to the code via `import sys` and then `sys.path.extend(['path_to_CorrNet']` ?

**Comment by yemenoglu** [comment]
Ok, i will try it, thank you.

**Comment by 847796207** [comment]
I encountered the same problem, did you solve this problem?

**Comment by hulianyuyy** [comment]
I suppose that this may be attributed to the version of python? 'dataset.dataloader_video' is a py file and you can normally import it by the import function in python.

**Comment by yemenoglu** [comment]
I m sorryfor late answering.
I didnt solve it and i tried son many things, but fail.
If you find anything, please share with me.
Thank you.

________________________________
Gönderen: quan ***@***.***>
Gönderildi: 29 Haziran 2023 Perşembe 10:49
Kime: hulianyuyy/CorrNet ***@***.***>
Bilgi: yemenoglu ***@***.***>; Author ***@***.***>
Konu: Re: [hulianyuyy/CorrNet] Training Problem (Issue #5)


I encountered the same problem, did you solve this problem?
