### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by Anysc-Bryant** [hulianyuyy/CorrNet#50]
Hello, I encountered some confusion while using netron to inspect the model structure. Could you please clarify if the input dimension of 1024x1296 for the provided pre-trained model pertains to the image size? Additionally, could you explain what is meant by 'output' in this context

**Comment by hulianyuyy** [comment]
Sorry, but i don't quite understand where is the 1024x1296 come from. Our model uses 224*244 images as inputs to process, as noted in the [dataloader_video.py](https://github.com/hulianyuyy/CorrNet/blob/main/dataset/dataloader_video.py#L97).
