### ISSUE TITLE
trainging time of  1 epoch on phoenix2014-T

### ISSUE THREAD

**Issue by Clouc-Catkin** [hulianyuyy/CorrNet#51]
Hi, I found that CorrNet need about 3 hours per epoch on phoenix2014-T when using 3090. But I place dataset files on Hard Disk with 7200 RPM. I wonder if this matters?

So I try to use joint coordinates instead of RGB to get a lightweight model with less training time. But I failed on the 3d hand joint data retrieved from RGB using Mediapipe. 

I would greatly appreciate it if you could provide relevant information about above two problems.

Best regard.

**Comment by hulianyuyy** [comment]
About training time, CorrNet costs about <20 minutes per epoch during training on a 3090. I speculate that long training procedure may be attributed to the data loading process which costs too much time, or maybe there exists other processes using the GPU.

About joint coordinates for phoenix2014-T dataset, i haven't tried it and may not provide guidance.
