### ISSUE TITLE
CSL txt

### ISSUE THREAD

**Issue by xuqico** [hulianyuyy/CorrNet#54]
Hi author, I would like to know how the order of sentences in txt in this CSL dataset is designed, is it randomized? Or is there some pattern, because I see that there seems to be no relationship between the sentence order and the folder video serial number.
[dev.txt](https://github.com/hulianyuyy/CorrNet/files/15397278/dev.txt)

**Comment by xuqico** [comment]
I was trying to express why it suddenly changed from video499 to video2950
![image](https://github.com/hulianyuyy/CorrNet/assets/130065791/aae649fb-eb10-4b04-944d-7abc932d358e)


> Hi author, I would like to know how the order of sentences in txt in this CSL dataset is designed, is it randomized? Or is there some pattern, because I see that there seems to be no relationship between the sentence order and the folder video serial number. [dev.txt](https://github.com/hulianyuyy/CorrNet/files/15397278/dev.txt)

**Comment by Coisini-Glenda** [comment]
@xuqico I wonder if you can provide me with the CSL-Daily data set? Email xiaofeihuang2021@163.com. Thank you so much!

**Comment by xuqico** [comment]
> I am not a contributor for the CSL dataset, which is developed by the USTC team. But as i observe, there seems to be no relationship between the sentence order and the folder video serial number.

Got it, thanks for the prompt reply

**Comment by xuqico** [comment]
> @xuqico I wonder if you can provide me with the CSL-Daily data set? Email [xiaofeihuang2021@163.com](mailto:xiaofeihuang2021@163.com). Thank you so much!

Sorry, I don't have the CSL-Daily dataset, this dataset will have to be requested from the original authors

**Comment by xuqico** [comment]
> @xuqico I wonder if you can provide me with the CSL-Daily data set? Email [xiaofeihuang2021@163.com](mailto:xiaofeihuang2021@163.com). Thank you so much!

Sorry, I don't have the CSL-Daily dataset, this dataset will have to be requested from the original authors
