### ISSUE TITLE
gloss_dict of phoenix2014-T

### ISSUE THREAD

**Issue by southnt** [hulianyuyy/CorrNet#55]
Can I ask a question.
As I check len(gloss_dict) of phoenix2014-T, I got 1115. But the paper mention that vocabulary of 1085 signs. What is different of vocabulary signs?

**Comment by hulianyuyy** [comment]
The number in the code is correct. This is wrongly reported in the paper.

**Comment by southnt** [comment]
I got it. Thanks!
