### ISSUE TITLE
Unsatisfied results on my own video

### ISSUE THREAD

**Issue by ruoqi77** [hulianyuyy/CorrNet#59]
Hello, I try to test my own chinese sign video with test_one_video.py using the pretrained CSL-Daily pth, but  never get the correct results. 
I wonder if you could provide several demo videos (maybe two or three is enough) which can produce the correct results for reference.
(My email dutlrq1103@163.com)

**Comment by hulianyuyy** [comment]
Sorry for the late response. The gloss vocabulary of CSL-Daily dataset may not be the same with your own chinese sign video. I have tested two videos from CSL-Daily, which show correct outputs as follows.
![image](https://github.com/hulianyuyy/CorrNet/assets/29403866/5369dd1a-8a84-4624-b4a6-2a5030fce736)
The videos are posted to your email.
