### ISSUE TITLE
Trainning problem

### ISSUE THREAD

**Issue by stevenGX24** [hulianyuyy/CorrNet#7]
I tried to train on CSL-Daily dataset, but it reported the error "list index out of range". It may be the problem in dataloader_video.py. I notice that you said, we need to  disable the temporal resampling strategy. How that actually been done? Should I comment the whole collate_fn function?

**Comment by hulianyuyy** [comment]
No, this is mostly attributed to that you haven't correctly set the path to CSL-Daily dataset.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 6, 2023 14:30 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [hulianyuyy/CorrNet] Trainning problem (Issue #7)




 
I tried to train on CSL-Daily dataset, but it reported the error "list index out of range". It may be the problem in dataloader_video.py. I notice that you said, we need to  disable the temporal resampling strategy. How that actually been done? Should I comment the whole collate_fn function?

**Comment by stevenGX24** [comment]
Do you mean I need to set the soft link to the sentence file?

**Comment by hulianyuyy** [comment]
Set the soft link to the dataset dir. You can follow the instructions for CSL-Daily dataset in the readme.md



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 6, 2023 14:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/CorrNet] Trainning problem (Issue #7)




 
Do you mean I need to set the soft link to the sentence file?

**Comment by stevenGX24** [comment]
OK, thanks.
